import SocialLink from '@/components/SocialLink';
import { Download, Fingerprint, Globe2, Mail, Smartphone } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';
import DetailHeader from '@/components/DetailHeader';
import Footer from '@/components/Footer';
import Image from 'next/image';
import { profile } from '@/lib/content';
import { MakerToolbox } from '@/components/CaseInteractions';
export const metadata: Metadata = { title: 'About — Web & Flutter Developer', description: 'Meet Azrul Mustaqqim, a developer in Terengganu building websites with React and Next.js and mobile apps with Flutter.', alternates: { canonical: '/about' }, openGraph: { title: 'About Azrul Mustaqqim', description: 'A little background, the work I do, and the tools I use.', url: '/about', images: ['/opengraph-image'] } };

export default function AboutPage() { return <><DetailHeader /><main id="main-content" className="detail-page maker-page"><div className="detail-shell"><header className="maker-hero"><div className="maker-heading"><p className="eyebrow">Meet the maker / Azrul Mustaqqim</p><h1>Curious mind.<br /><span>Busy hands.</span></h1></div><div className="maker-photo"><Image src="/azrul-image.jpg" alt="Azrul Mustaqqim in Terengganu" width={720} height={1280} sizes="(max-width: 767px) 85vw, 450px" priority /><span className="maker-location">TERENGGANU, MALAYSIA</span></div><div className="maker-intro"><Fingerprint className="maker-fingerprint" size={78} strokeWidth={1.3} aria-hidden="true" /><p>I&rsquo;m Azrul, a web and Flutter developer. I turn ideas into interfaces people can use.</p><p>As a fresh graduate, I&rsquo;m building my skills through hands-on projects from programme landing pages to mobile product catalogs.</p><a className="play-button" href="/resume.pdf" download>Download résumé <Download size={16} strokeWidth={1.5} aria-hidden="true" /></a></div></header><section className="maker-manifesto"><p className="eyebrow">What keeps me building</p><h2>Understand the problem.<br />Give it structure.<br /><span>Refine the little things.</span></h2><p>I enjoy figuring out how things work, then turning that understanding into something useful. Each project is a chance to learn through making.</p></section><section id="capabilities" className="maker-capabilities"><p className="eyebrow">What I build</p><h2>Two mediums.<br />One hands-on approach.</h2><div className="maker-work-grid"><Link href="/work/ranaco"><span className="eyebrow">01 / Web development</span><Globe2 className="capability-symbol" size={48} strokeWidth={1.5} aria-hidden="true" /><h3>Made for<br />the browser.</h3><p>Responsive websites and landing pages with React, Next.js, and TypeScript.</p><strong>Explore Ranaco →</strong></Link><Link href="/work/product-catalog"><span className="eyebrow">02 / Mobile development</span><Smartphone className="capability-symbol" size={48} strokeWidth={1.5} aria-hidden="true" /><h3>Built for<br />your pocket.</h3><p>Flutter interfaces connected to REST APIs, with search, pagination, and clear request states.</p><strong>Explore Product Catalog →</strong></Link></div></section><MakerToolbox /><section className="maker-contact"><p className="eyebrow">Open to roles & projects</p><h2>Let&rsquo;s make<br />something useful.</h2><div className="button-row"><Link href="/#contact" className="play-button">Let&rsquo;s talk <Mail size={16} strokeWidth={1.5} aria-hidden="true" /></Link><SocialLink platform="github" href={profile.github} /><SocialLink platform="linkedin" href={profile.linkedin} /></div></section></div></main><Footer /></>; }